### ISSUE TITLE
🐛Bug: keyboard navigation with tab key includes too many stops in some components

### ISSUE THREAD

**Issue by pawelblaszczyk5** [melt-ui/melt-ui#127]
**Describe the bug**
Hello 👋
At the beginning I want to mention that you're doing an awesome job with the library and I'm stoked for its potential as the go-to Svelte UI solution 😇 There're a few components with problems and I weren't sure will it be better to open one or multiple issues. If you'd prefer to have multiple, just let me know and I can split them.

It seems like some of the components include too many tab stops. It's mostly related to components where there is also arrow navigation. I'm not 100% sure about the correct ARIA patterns, but as far as I checked it and compared it to other libs (radix, react-aria, zag.js, ariakit) here are the components that seems to be affected:

- [x] Select - tabbing should close the select and focus the next available element - #131
- [x] Toggle Group - tabbing shouldn't cycle between all toggles, it should focus the next available element - #133 
- [x] Toolbar - same case as Toggle Group - #135 
- [x] Tags Input - this one I'm not 100% sure, because I couldn't find aria pattern for this, but from comparison to other libs it seems like usually the whole component is only one tab stop and you can use arrows to cycle between tags and input - #124 
- [x] Dropdown Menu - it seems like it completely traps focus on the trigger. Also, the keyboard navigation seems to act like it's modal - you can't navigate out of it without pressing escape and tab do nothing - it seems to be modeled after Radix. - However, in Radix these are rendered as modals by default - you also can't press away with mouse, you can't scroll, etc. In Melt UI it isn't modaled. Implementation of this component seems to have the most differences between libraries 😅 - #137 
- [x] Menubar - this one is currently on the PR, but same case as in toolbar/toggle group. I've used Radix as a reference in these - #126 

**To Reproduce**
1. Go to page of the specific component 
2. Navigate the examples with keyboard
3. See specific errors

**Expected behavior**
I've described them above

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS 14.0 Beta
 - Browser: Safari
 - Version: 17.0 (19616.1.17.11.4)

I've tested also in Chrome, latest version and it seems like a bug related to implementation and unrelated to specific platform

**Additional context**
For reference the Radio Group which shares the expected behavior it seems to be modeled correctly

**Comment by huntabyte** [comment]
Hey, @pawelblaszczyk5 thanks for the issue!

These components are extremely difficult to build, especially headless so I appreciate the patience! The reason we've released them already is to get feedback like this and improve on the cases that we haven't considered/extensively tested, and so far the feedback we've been getting is great!

Going to address a few of them here but I'll open up issues to get these worked out.

### Select
Radix doesn't close the Select on `Tab`, which is what we've modeled it around but I agree that this should probably be the case, especially when referencing this [example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/).

### Dropdown Menu
There's a PR open that will fix and add the modal behavior for the dropdown menu and menubar, as far as the focus being trapped on the trigger, that's something separate we'll have to work out :)

**Comment by pawelblaszczyk5** [comment]
Yup, I completely understand how hard is to get them right. Apologize if I've sound pretentious or something, you're doing awesome job with this!

**Comment by huntabyte** [comment]
You don't sound pretentious at all! This is exactly the type of reports/issues we want to be raised so we can address them, so thanks a ton for taking the time to open it!

**Comment by huntabyte** [comment]
To see the updated context/dropdown menus with the modal behavior, here's a preview link: https://melt-emwnskd72-melt-ui.vercel.app/docs/builders/dropdown-menu

Still doesn't address the trigger focus trap, but I'm on it!

**Comment by huntabyte** [comment]
Okay, I think with the outstanding PRs, all of these issues _should_ be addressed. If you wouldn't mind giving them a peep when you get the chance @pawelblaszczyk5 for a second set of eyes/hands! Thanks again for bringing this to our attention!

Here are the latest previews for each:
- **Select**: https://melt-gvcye50h7-melt-ui.vercel.app/docs/builders/select
- **Toggle Group**: https://melt-o4wg6ygrp-melt-ui.vercel.app/docs/builders/toggle-group
- **Toolbar**: https://melt-h79r8mgi9-melt-ui.vercel.app/docs/builders/toolbar
- **Dropdown Menu**: https://melt-4k7ctgv7n-melt-ui.vercel.app/docs/builders/dropdown-menu
- **Menubar**: https://melt-ns8896zz7-melt-ui.vercel.app/docs/builders/menubar

**Comment by pawelblaszczyk5** [comment]
Oh, you're crazy fast, awesome job 😍 I didn't expect such a fast resolution, I'm stoked, thanks a lot!

One issue and one small improvement that I noticed.

- Dropdown menu, when I open it with keyboard and then close it with tab or shift-tab, it seems to be stack with tabindex -1 and it can't be focused by keyboard until I open it with mouse
- Toggle group, we could focus the active one if it's available, I think that's a good a11y win, Radix do the same as well

Once again, I'm really impressed and thanks a ton!

**Comment by huntabyte** [comment]
Thanks for the kind words! 

I'm not able to produce the issue you're describing with the dropdown menu @pawelblaszczyk5 - check the live https://melt-ui.com/docs/builders/dropdown-menu.

Maybe a PR has been merged since you checked that addresses it? If not, let me know and I'll look into it further!

As for the toggle group, I agree with that, let me look into it!

**Comment by TGlide** [comment]
@pawelblaszczyk5 stated the issue still persists

**Comment by pawelblaszczyk5** [comment]
Yup, the last part about dropdown menu being stuck on tabindex `-1` after being closed via tabbing out of it seems to still exist on the #168 branch. I've opened the docs from Vercel deployment on this PR and I can still reproduce it

**Comment by huntabyte** [comment]
@pawelblaszczyk5 Can you give me an exact reproduction with key sequence etc.?

**Comment by pawelblaszczyk5** [comment]
I think this will be sufficient - https://www.youtube.com/watch?v=ayqnafpcXuY (apologizes for my english accent 😅 )

**Comment by huntabyte** [comment]
@pawelblaszczyk5 incredible @pawelblaszczyk5 , I wish videos were provided like this for all reproductions :) also, your accent is great!

**Comment by huntabyte** [comment]
Fun fact, this bug only exists on firefox which is why I had such a hard time reproducing 😆 @pawelblaszczyk5

**Comment by pawelblaszczyk5** [comment]
> Fun fact, this bug only exists on firefox which is why I had such a hard time reproducing 😆 @pawelblaszczyk5

Oh, this one I've tested only on Safari (you can count this one too then), sorry 😄

**Comment by huntabyte** [comment]
**Only exists on non-chromium! I'm on it!
