### ISSUE TITLE
✅Pre-1.0 checklist

### ISSUE THREAD

**Issue by TGlide** [melt-ui/melt-ui#148]
## ✅ Add new Builders
- [X] Combobox
- [X] Pin Input
- [x] Toast
- [x] Table of Contents - #264 

## Builder tasks
- [x] Accordion
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [X] CSS examples
- [x] Avatar
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [X] Tests
  - [x] CSS examples
- [x] Checkbox
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [X] CSS examples
- [x] Collapsible
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [X] Tests
  - [x] CSS examples
- [ ] Context Menu
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Combobox
  - [ ] Builder Wrapper
  - [ ] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [x] Dialog
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [x] CSS examples
- [ ] Dropdown Menu
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Hover Card
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Label
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Menubar
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [x] Pagination
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [x] CSS examples
- [ ] Pin Input
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [ ] Popover
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Progress
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [ ] Radio Group
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [ ] Select
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [ ] Separator
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Slider
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Switch
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Tabs
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [ ] Tags Input
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [ ] Toggle
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [ ] Tests
  - [ ] CSS examples
- [ ] Toggle Group
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Toolbar
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples
- [ ] Tooltip
  - [X] Builder Wrapper
  - [X] Export `Args` and `Returned` types
  - [x] Tests
  - [ ] CSS examples

## ✅ Preprocessor
Related #100 

- [X] Released pp
- [x] Melt initialization script with PP option

## ✅ Controlled APIs
- [x] The Big Bad #234

## Docs
- [ ] Auto-docs
- [ ] Separate examples
- [ ] Search

**Comment by geerew** [comment]
#158 so fill out the major of the `Migrate builders to use the builder wrapper` section ..
